image:
  repository: chrish1979/sysmon-api
  tag: 27b2b5011297c51096bb9a64811db30c0da2b88e
  pullPolicy: Always

service:
  port: 8000

domain: sysmon.local

canary:
  enabled: true
  trafficPercent: 10
  stableRevision: sysmon-api-api-368871c7

postgres:
  image: postgres:16
  database: sysmon
  user: sysmon
  password: sysmon
  storage: 1Gi
