image:
  repository: chrish1979/sysmon-api
  tag: 287d053b44a0809b6c1e87476cbd5e6b0c2f3940
  pullPolicy: Always

service:
  port: 8000

domain: sysmon.local

canary:
  enabled: true
  trafficPercent: 10
  stableRevision: sysmon-api-api-287d053b

postgres:
  image: postgres:16
  database: sysmon
  user: sysmon
  password: sysmon
  storage: 1Gi
