apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sysmon-api
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            namespace: dev
            domain: sysmon-dev.local
          - env: staging
            namespace: staging
            domain: sysmon-staging.local
          - env: prod
            namespace: prod
            domain: sysmon.local
  template:
    metadata:
      name: "sysmon-api-{{env}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/chrish1979/sysmon-api.git
        targetRevision: HEAD
        path: helm/sysmon-api
        helm:
          valueFiles:
            - values.yaml
            - "values-{{env}}.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
        syncOptions:
          - RespectIgnoreDifferences=true
          - CreateNamespace=true
      ignoreDifferences:
        - group: serving.knative.dev
          kind: Service
          jsonPointers:
            - /spec/template/spec/containers/0/readinessProbe
