apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-api-{{ .Values.image.tag | trunc 8 | trimSuffix "-" }}
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - name: sysmon-api
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: DB_HOST
              value: {{ .Release.Name }}-postgres
            - name: DB_NAME
              value: {{ .Values.postgres.database }}
            - name: DB_USER
              value: {{ .Values.postgres.user }}
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres-secret
                  key: postgres-password
            - name: VERSION
              value: {{ .Values.image.tag | trunc 8 | quote }}
            - name: CHAOS_RATE
              value: {{ .Values.chaos.rate | quote }}
            - name: ENVIRONMENT
              value: {{ .Release.Namespace | quote }}
  traffic:
    {{- if .Values.canary.enabled }}
    - latestRevision: true
      percent: {{ .Values.canary.trafficPercent }}
    - latestRevision: false
      revisionName: {{ .Values.canary.stableRevision }}
      percent: {{ sub 100 .Values.canary.trafficPercent }}
    {{- else }}
    - latestRevision: true
      percent: 100
    {{- end }}